### ISSUE TITLE
Can't start scheduler (Solved)

### ISSUE THREAD

**Issue by mjsmitty** [redteamsecurity/PlugBot-Plug#3]
I'm trying to set up a test bot on my network but i cant seem the get the scheduler to start. Currently it can check in to the C2C and when i click "Start the Scheduler" a green box appears that says "Scheduler was started", but under the "Deployment Checklist" it says "Scheduler is Disabled!". The bot wont automatically check in to the C2C for applications and jobs.

**Comment by redteamsecurity** [comment]
@mjsmitty didn't see this. still having issues?

**Comment by mjsmitty** [comment]
Yes, I am still having issues with the bot.  I have cron installed i can test the connection and it shows in the logs on the C2C. I am using a Raspberry Pi as the bot.

**Comment by redteamsecurity** [comment]
try running this from the command line

`crontab -u www-data /var/www/cron/cron.txt`

**Comment by mjsmitty** [comment]
Ok thank you that fixed the problem for the scheduler.  The bot also isn't downloading the scripts. The bot says type 300 Downloaded 1 app(s) and the C2C says Code: 500	APP: Displayed 1 app(s), but the app still is pending. I have tried to put the script in a zip and not in a zip i have also put the file on a ftp server and web server.

**Comment by redteamsecurity** [comment]
@mjsmitty sounds like a permissions issue. In order to download and install scripts, the user running the apache2 service (presumably "www-data") should be configured with permissions to (recursively) create files and folders under /var/www/apps  -- this is where scripts are downloaded, unzipped, stored, executed, etc.

**Comment by mjsmitty** [comment]
I changed the permissions of the www/ folder to www-data and it downloaded the file to the root of the web server and didn't unzip the program.  Could this be a problem with the new version of apache having the webserver be under "/var/www/html/"? The bot is also redownloading the zip each time and nameing the test.zip.1 test.zip.2 ...

**Comment by redteamsecurity** [comment]
@mjsmitty first off, be sure you have Flip installed on the bot

secondly, it should not be downloading in the root. your path for the PlugBot app should be /var/www/ and the apps should be going into /var/ww/apps. do you have an apps filder?

**Comment by mjsmitty** [comment]
Flip is installed and when i put the web files in the "/var/www/" directory they don't show up on the browser they have to be in the "/var/www/html" directory.
![pi](https://cloud.githubusercontent.com/assets/4917593/18299320/99100512-7474-11e6-8beb-04b51413fc16.PNG)

**Comment by redteamsecurity** [comment]
when you say, they don't show up on the browser... do you mean web browser directory listing?

**Comment by mjsmitty** [comment]
I'm sorry for the confusion i meant the web browser.

(when the web server is in this directory "/var/www")
![pi2](https://cloud.githubusercontent.com/assets/4917593/18299967/e6c95eac-7479-11e6-8193-b21c96b12d65.PNG)

(the web browser shows this)
![pi3](https://cloud.githubusercontent.com/assets/4917593/18299982/0f71d60e-747a-11e6-9045-a561d85436d7.PNG)

**Comment by mjsmitty** [comment]
I edited the "/etc/apache2/sites-available/000-default.conf" file and changed "DocumentRoot /var/www/html" to "DocumentRoot /var/www" and move the web server to that directory and now the program seems to download and unzip. The bot seemed to have ran the script, but when it tried to tell the C2C the log says:

09/06/16 9:46:01 PM	ROOM	Code: 200	CHECK-IN: Bot check in from: 192.168.1.224
09/06/16 9:46:01 PM	[[[ UNIDENTIFIED BOTKEY ]]]	Code: 445	ERROR: tried to save job output

The bot seemed to have lost its key when uploading to the C2C.

![pi4](https://cloud.githubusercontent.com/assets/4917593/18300288/afd8b034-747c-11e6-8e04-0e59af9a5451.PNG)

![pi5](https://cloud.githubusercontent.com/assets/4917593/18300290/b4695248-747c-11e6-8d39-1a92356fb8cf.PNG)

**Comment by mjsmitty** [comment]
Never mind i realized the times were not the same on both machines and i changed them to match.  Thank you for all the help with getting this to work.

**Comment by redteamsecurity** [comment]
that's great! let us know if  you have other questions
