### ISSUE TITLE
Issues getting this to run on Raspberry Pi 2 or 3

### ISSUE THREAD

**Issue by arbogajk** [redteamsecurity/PlugBot-Plug#5]
I am trying to use this for a project in a networking and cyber security class.  We have been struggling to get the PlugBot(bot) portion to run on both a Pi 2 and Pi 3.  After installing all the required packages and setting up the mysql database and running the script and editing the database.php with our password, going to the the url for the Pi displays a blank page.  All of the web application files for the PlugBot are in /var/www.  

On the github issues page for the C2C portion, there is a lot of talk about the .htaccess file being in the root directory of the web server.  Is this required on the bot portion of the application as well or just the C2C server?  Any other suggestions for troubleshooting?

**Comment by phazed0** [comment]
I am also having the same issue. I get a blank white page when trying to go to index.php.

I THINK I have narrowed it down to being a PHP7.0 issue where the mysql_* functions have been deprecated and that perhaps mysqli_* functions should be used instead. Not a coder, no idea really - just read it on on stackoverflow:
http://stackoverflow.com/questions/34579099/fatal-error-uncaught-error-call-to-undefined-function-mysql-connect

I have tried finding a solution to installing PHP5.6 on Kali 2 but it doesn't look like it's possible (I tried a few tips from weezy deb packs but still no joy, they fail).

Might have to downgrade to an older version of Linux to get this going, as it sits.

**Comment by arbogajk** [comment]
I have PHP5.6 on 2 of my Raspberry Pi's and it still doesn't work.  Not sure it's an issue with PHP7.0 since I have tested it with PHP5.6 on the Pi's. I am also thinking maybe it could be an issue with iptables possibly, but have no idea.  We had trouble getting the server portion to run on Ubuntu Server 16.04 as well, and then we found a post about using Turnkey Linux Lamp Stack VM and that worked getting the C2C web page to load.  I am thinking it is some sort of configuration issue maybe with Apache or something else.  I checked the versions of everything installed on the Lamp Stack VM and we were running all the same versions of everything, which is why I believe it is a configuration issue.  Might start examining the Apache2 config file on the Lamp Stack VM and compare it to Raspberry Pi Apache2 configuration.  Let me know if you find anything else out that might be helpful to look into.

**Comment by phazed0** [comment]
If I change line 21 in index.php to be 'development' (For error output) I get the following - which is otherwise the blank white page:

Fatal error: Uncaught Error: Call to undefined function mysql_pconnect() in /var/www/html/system/database/drivers/mysql/mysql_driver.php:92 Stack trace: #0 /var/www/html/system/database/DB_driver.php(116): CI_DB_mysql_driver->db_pconnect() #1 /var/www/html/system/database/DB.php(149): CI_DB_driver->initialize() #2 /var/www/html/system/core/Loader.php(347): DB(Array, NULL) #3 /var/www/html/system/core/Loader.php(1172): CI_Loader->database() #4 /var/www/html/system/core/Loader.php(153): CI_Loader->_ci_autoloader() #5 /var/www/html/system/core/Controller.php(52): CI_Loader->initialize() #6 /var/www/html/system/core/CodeIgniter.php(309): CI_Controller->__construct() #7 /var/www/html/index.php(202): require_once('/var/www/html/s...') #8 {main} thrown in /var/www/html/system/database/drivers/mysql/mysql_driver.php on line 92

I have verified via MySQL CLI and myphpadmin that the db_plugbot_client database exists and is active (At least that seems to be what I take away from it anyways).
The fatal error "Call to undefined function mysql_pconnect()" is what led me to believe the stackoverflow comments about mysql_* deprecated issue. From what I read, perhaps we need to try MariaDB which is more or less backwards compatible with 'older' db commands? Dunno... rabbit hole...

**Comment by phazed0** [comment]
Tried Turnkey Linux Lamp Stack with the same results - however, if I try putting the project into development mode I get no error like I do with the straight up Pi LAMP setup - simply a blank page yet again. So, it's not just you, FYI. ;-)

**Comment by arbogajk** [comment]
Yea I previously tried running the Bot portion on the Turnkey Lamp statck, since the C2C code seemed to run when using it, but I had no luck either.  I do not get that error when I change it from production to development on line 21 in the index.php.  It still just displays a blank page.  And using curl -v <ip address> gives 200 OK code, but there is no body after the html header.

**Comment by arbogajk** [comment]
I just got it to run on my Raspberry Pi.  I found that in the config.php file for the $config['base_url'] = line at the top, I had 'http://localhost/';.  I changed the single quotes to "" double quotes and notices that //localhost/ was in blue text(meaning a comment in Nano).  I changed it to 'http:\/\/localhost/' to escape the forward slashes and now the page loads.  Not sure if that will help you out, but it solved my problem.

**Comment by arbogajk** [comment]
Actually I just checked it again with what I had before and it worked.  I did got to the url in the web browser http://<my IP address>/index.php/home/setup and I had the login page.

**Comment by phazed0** [comment]
You get a GOLD medal my friend! Fantastic find! That did work, plus a had another silly thing...

I'm running php7.0 and I was trying to figure a way to use mysql when all I had to do is change in config.php:
$db['default']['dbdriver'] = 'mysql';
to
$db['default']['dbdriver'] = '**mysqli**';

What a 'duh' moment!

So yeah, now I have a page and can login. Thanks again!

**Comment by arbogajk** [comment]
Glad to help.  I've been struggling to get it to work for like a week now.  I have run into another issue, not sure if you're at this point yet, but I'll throw it out there and maybe we can figure it out together.  I have successfully got the bots to check in to the C2C and was able to install some of the sample scripts the guys at Red Team Security provided, but when running the jobs on the PI and selecting the output option to upload output to C2C....It just sits there forever saying "Running job" and never uploads to the C2C, so I can't click the view results button like Jeremiah shows in his videos.  When I select the output option to save locally to the bot it works, but I have no idea where the output is saved to on the bot.  I feel like maybe there is a permissions issue with a folder or something on the C2C which is why the bot never successfully uploads the results, but I don't know what folder it is suppose to save to on the C2C.  Let me know if you get to this point and have the same issue.

**Comment by phazed0** [comment]
Still struggling. Thought that was going to be it! It sounds like you have gone a little farther than I have.

I have the C2C up and running after a bit of work. I was getting a mysql error 1364 on the C2C but fixed that by removing STRICT_TRANS_TABLES from the SQL mode as seen here:
http://stackoverflow.com/questions/15438840/mysql-error-1364-field-doesnt-have-a-default-values

The Pi bot is up as well, yay! I seem to have everything configured correctly in the www UI's and the Bot CAN connect to the C2C using "Test Bot Check-In Connectivity" and the C2C makes a log noting it saw the bot, however, that's all. 
I cannot seem to upload a script and the bot is empty of any default scripts (I thought it came with some by default?). I also cannot start the scheduler... it says it is started but if I go directly to the bot "Checklist" after turning it on, it reports it is Disabled. I feel that in my case the scheduler not starting is why I cannot get the script to download from the C2C.

Since I seem to be a step behind you I can't say for sure about the job results location, but would they not go to the defined "dropzone" folder?

**Comment by arbogajk** [comment]
I know exactly what's wrong with the script install and scheduler on the bots... I found this post about https://github.com/redteamsecurity/PlugBot-Plug/issues/3.  I will make it shorter for you.  
First make sure you have cron and flip installed on the raspberry pi.  Next you need to change the permissions of the the /var/www/apps folder.  Use the command sudo chgrp www-data /var/www/apps or if you have the web application in the html directory for apache it would be /var/www/html/apps.  Next use the command sudo chmod -R g+rwxs /var/www/apps.  This gives the apache2 user group read write and execute permissions on the apps folder.  To get the scheduler problem sorta out you need to run the command sudo crontab -u www-data /var/www/cron/cron.txt.  I believe this assigns the apache2 user to cron.  Let me know if this doesn't help you out, but I think it will solve your problem with installing the apps

**Comment by arbogajk** [comment]
Almost forgot....The perl scripts don't come with the git download.  I found them here https://gist.github.com/redteamsecurity.  Make sure you zip them up before getting the bots to download them.  Follow some of the videos on the redteamsecurity's webpage.  I tried to point the bots to a mediafire link to download the scripts and also github, but it would not work so I created a local ftp server and after configuring a directory on it to be for anonymous users I pointed the bots to the link ftp://ipaddress/thediretoryname and they were able to download the scripts.

**Comment by phazed0** [comment]
OK, that worked mostly. flip and cron were installed, i didn't chmod -R g+rwxs the apps dir - so thanks for that tip from post #3. In addition to that problem I had to move the bot files from /var/www/html to /var/www  and configure apache2/ssl conf files to work from there - only then would the zip files seem to transfer and work. 

I am now able to get the programs to the Pi and can execute jobs, but like you, cannot get the output of those jobs to the C2C... C2C logs an error:
[[[ UNIDENTIFIED BOTKEY ]]]	Code: 445	ERROR: tried to save job output

which happens to be the same error mjsmitty got at the end of the #3 post:
https://github.com/redteamsecurity/PlugBot-Plug/issues/3

He says he was able to rectify his issue by making sure the time was the same on both the C2C and bot - I have done the same but still get the issue.

**Now here's a funny exception to that problem:**
If I run the hello_world.sh job I DO GET A JOB OUTPUT TO THE C2C! On the manage jobs page I get a status of Output Received and can view "Hello World".

I have tried the ping and nmap tests so far and they fail with the UNIDENTIFIED BOTKEY error on C2C... so close.

**Comment by arbogajk** [comment]
I am starting to think it is a root permissions problem.  I have to use sudo to run the hping3 perl script locally on the bot, so I'm not sure how the bot could executes the perl script without root permission when the C2C issues the job.  I think that might be why it's hanging up.  It can't execute the hping3.pl script without sudo.

**Comment by redteamsecurity** [comment]
All,

these are the first of several video tutorials. I hope they're helpful.

https://www.youtube.com/playlist?list=PLnyNNzQS9zzHCKSMMLGWgYiVn5qt90rpO

Thanks,
RedTeam Security

**Comment by johanbroersma** [comment]
@arbogajk I have the same issue where i get the error:

[[[ UNIDENTIFIED BOTKEY ]]] Code: 445 ERROR: tried to save job output

I am also running the bot on a raspberry pi and have tried several things. In my case I cannot get the hello world script to upload either.

Do you have any insight that may help me?

Thank you!

**Comment by arbogajk** [comment]
@johanbroersma I set this up as part of a project at James Madison University and got it working on the raspberry PI's.  I set up a git repo with the instructions at https://github.com/arbogajk/PlugBot-Setup-Instructions.  I believe the steps for setting up the PI are in Exercise 1, Step 2 of the ISAT460_SP_Lab_Instructions_Template_1.pdf file in the repository.  That should help you out as I ran into all these problems, but eventually got it working.  Try to follow the instructions step by step and you should get it working.  If you have any other questions let me know and I'll try to help out.

**Comment by johanbroersma** [comment]
@arbogajk Amazing! I just read over the material - hopefully it will help bring my setup to life. Will let you know tomorrow.

**Comment by johanbroersma** [comment]
@arbogajk I followed the steps you did in your paper (which is very descriptive) but still no joy...

![image](https://cloud.githubusercontent.com/assets/9388167/25387534/2d3c0f7c-2999-11e7-9a95-336545064e85.png)

Any ideas?

**Comment by johanbroersma** [comment]
@arbogajk as a follow up - I re-did the plugbot-plug (raspberry pi) and the plugbot-c2c (now running on Ubuntu 14.04) and followed the steps very carefully. Still no luck getting rid of the "unidentified botkey" error in the log...

**Comment by johanbroersma** [comment]
As an update, I modified the code in job.php on the C2C and added the following code at line 32

`if ($output == '')
        {

        // Log action in case the output was empty
            $this->log_model->log_checkin($botkey,'446','Received job out$

        }`

This showed me that exact error in the logs. This means that the output being received from the bot is actually empty. I also discovered that if I save the output locally on the bot, the file is also empty...

I will attempt to run another script to see if I get the same error - but now I know I need to look at the bot - not the server :D

**Comment by johanbroersma** [comment]
UPDATE:

I have added some code to log the strings are they are created by process_control.php. The exec_dir and full_cmd are correct, but the php script is not capturing the output from the command. I have also tried running the command as www-data which runs successfully.

Will continue troubleshooting.

![selection_002](https://cloud.githubusercontent.com/assets/9388167/25431328/78e8ec02-2a56-11e7-8927-ab174737ae9e.png)

**Comment by johanbroersma** [comment]
UPDATE:

I changed line 860 in process_control.php to:

`$output = shell_exec("$full_cmd 2>&1");`

Which is now giving me the following output:

![selection_003](https://cloud.githubusercontent.com/assets/9388167/25431895/cf5c99ba-2a58-11e7-96b3-e90ed3b8a1ea.png)

Seems that the application is stored in some ridiculously long stringed folder:

![selection_004](https://cloud.githubusercontent.com/assets/9388167/25431943/0297e38e-2a59-11e7-9bdb-55a5f290d336.png)

Onto checking the app downloading code...

**Comment by johanbroersma** [comment]
...found the issue:

It seems that after the bot downloads the app from C2C it unzips the file into this long stringed directory. The execution of the code is looking for the script in the apps/app_name.app_random folder, but cannot find it because the unzip put it in another subfolder...

to find this issue I copied the script to the apps/app.name.app_random directory and ran the job again. This time with much success. I wonder if we need to specify a syntax not to unzip the file in a subdirectory?

**Comment by johanbroersma** [comment]
So...that was NOT the problem...the issue was that my zip files had sub-directories. I needed to unzip the downloaded zip files, and re-zip them before putting them on the public server for downloading by the bot.

All is well and working now :dancer:
